[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Templates/OpenWorld
EditorStartupMap=/Engine/Maps/Templates/OpenWorld
GlobalDefaultGameMode=/Script/Parabellum.PBLGameMode

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/Engine.RendererSettings]
; Экспозицию фиксируем вручную: авто-экспозиция разъедется между тремя
; рендерами на Э6 и даст видимые швы.
r.DefaultFeature.AutoExposure=False
; Никакой бодикам-эстетики - картинка чистая, как в CS.
r.DefaultFeature.MotionBlur=False
; TSR
r.AntiAliasingMethod=4
r.Lumen.HardwareRayTracing=False
