[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Templates/OpenWorld
EditorStartupMap=/Engine/Maps/Templates/OpenWorld
GlobalDefaultGameMode=/Script/Parabellum.PBLGameMode

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/Engine.RendererSettings]
; Экспозицию фиксируем вручную: авто-экспозиция разъедется между тремя
; рендерами на Э6 и даст видимые швы.
r.DefaultFeature.AutoExposure=False
; Никакой бодикам-эстетики - картинка чистая, как в CS.
r.DefaultFeature.MotionBlur=False
; TSR
r.AntiAliasingMethod=4
r.Lumen.HardwareRayTracing=False

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=6CCA0BF84ECB5E9AE1D1169AA0B3A815
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


[Core.Log]
LogEnhancedInput=VeryVerbose
